---
# tasks file for ansible-role-pipenv

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ pipenv_log_dir }}"
    mode: 0755
    owner: "{{ pipenv_user }}"
    group: "{{ pipenv_group }}"
    state: directory
  notify: Restart pipenv

- name: Create db directory
  file:
    path: "{{ pipenv_db_dir }}"
    mode: 0755
    owner: "{{ pipenv_user }}"
    group: "{{ pipenv_group }}"
    state: directory
  notify: Restart pipenv

- name: Create pipenv.conf
  template:
    src: pipenv.conf.j2
    dest: "{{ pipenv_conf_file }}"
    validate: echo %s
  notify: Restart pipenv

- name: Start pipenv
  service:
    name: "{{ pipenv_service }}"
    enabled: true
    state: started
