---
# tasks file for ansible-role-pipenv

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Setup pipenv environment"
  include_tasks: pipenv.yml
  loop: "{{ pipenv_environments }}"
  loop_control:
    loop_var: __pipenv
